lib/buru_web/router.ex
defmodule BuruWeb.Router do
  use BuruWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", BuruWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/posts", PostController do
      post  "/comment", PostController, :add_comment
      end
      resources "/comments", CommentController
      resources "/categories", CategoryController
  end

  # Other scopes may use custom stacks.
  # scope "/api", BuruWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: BuruWeb.Telemetry
    end
  end
end

lib/buru/news/post.ex
defmodule Buru.News.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Buru.News.{Comment, Category}

  schema "posts" do
    field :body, :string
    field :title, :string
    has_many  :comments, Comment
    belongs_to :category, Category
    timestamps()
  end

  @doc false
  def changeset(post, attrs) do
    post
    |> cast(attrs, [:title, :body, :category_id])
    |> validate_required([:title, :body, :category_id])
  end
end

lib/buru_web/controllers/post_controller.ex
defmodule BuruWeb.PostController do
  use BuruWeb, :controller

  alias Buru.News
  alias Buru.News.{Post, Comment, Category}
  alias Buru.Repo

  def index(conn, _params) do
    posts =
      News.list_posts()
      |> Repo.preload([:category])
      |> IO.inspect()

    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = News.change_post(%Post{})
    categories = Repo.all(Category) |> Enum.map(&{&1.title, &1.id})
    render(conn, "new.html", changeset: changeset, categories: categories)
  end

  def create(conn, %{"post" => post_params}) do
    case News.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        categories = Repo.all(Category) |> Enum.map(&{&1.title, &1.id})
        render(conn, "new.html", changeset: changeset, categories: categories)
    end
  end

  def show(conn, %{"id" => id}) do
    post =
      id
      |> News.get_post!()
      |> Repo.preload([:comments])

    changeset = Comment.changeset(%Comment{}, %{})
    category = Repo.get(Category, post.category_id)
    render(conn, "show.html", post: post, changeset: changeset, category: category)
  end

  def edit(conn, %{"id" => id}) do
    post = News.get_post!(id)
    changeset = News.change_post(post)
    categories = Repo.all(Category) |> Enum.map(&{&1.title, &1.id})
    render(conn, "edit.html", post: post, changeset: changeset, categories: categories)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = News.get_post!(id)

    case News.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, %Ecto.Changeset{} = changeset} ->
        categories = Repo.all(Category) |> Enum.map(&{&1.title, &1.id})
        render(conn, "edit.html", changeset: changeset, categories: categories)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = News.get_post!(id)
    {:ok, _post} = News.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: Routes.post_path(conn, :index))
  end

  def add_comment(conn, %{"comment" => comment_params, "post_id" => post_id}) do
    post =
      post_id
      |> News.get_post!()
      |> Repo.preload([:comments])

    case News.add_comment(post_id, comment_params) do
      {:ok, _comment} ->
        conn
        |> put_flash(:info, "Added comment!")
        |> redirect(to: Routes.post_path(conn, :show, post))

      {:error, _error} ->
        conn
        |> put_flash(:error, "Oops! Couldn't add comment!")
        |> redirect(to: Routes.post_path(conn, :show, post))
    end
  end
end

lib/buru_web/views/post_view.ex
defmodule BuruWeb.PostView do
  use BuruWeb, :view
  alias Buru.News

	def get_comments_count(post_id) do
		News.get_number_of_comments(post_id)
	end
end

lib/buru_web/templates/post/comment_form.html.eex
<h4>Add Comment</h4>
<%= form_for @changeset, @action, fn f -> %>
	<div class="form-group">
		<label>Name</label>
		<%= text_input f, :name, class: "form-control" %>
	</div>
	<div class="form-group">
		<label>Content</label>
		<%= textarea f, :content, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= submit "Add comment", class: "btn btn-primary" %>
	</div>
<% end %>

lib/buru_web/templates/post/comments.html.eex
<h4>Comments</h4>
<div class="comments">
	<div class="comment header">
		<div>Name</div>
		<div>Content</div>
	</div>
	<%= for comment <- @comments do %>
	<div class="comment">
		<div><%= comment.name %></div>
		<div><%= comment.content%></div>
	</div>
	<% end %>
</div>

lib/buru_web/templates/post/edit.html.eex
<h3>Edit Post</h3>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/buru_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>


  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <%= label f, :category_id  %>
  <%= select f, :category_id, @categories, style: "display: block;"  %>

  <div>
    <%= submit "Save" %>
  </div>
<% end %>

lib/buru_web/templates/post/index.html.eex
<h3>Listing Posts</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Category</th>
      <th>Comments</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
<%= for post <- @posts do %>
    <tr>
      <td><%= post.title %></td>
      <td><%= post.body %></td>
      <td><%= post.category.title %></td>
      <td><%= get_comments_count(post.id) %></td>
      <td>
        <span><%= link "Show", to: Routes.post_path(@conn, :show, post) %></span>
        <span><%= link "Edit", to: Routes.post_path(@conn, :edit, post) %></span>
        <span><%= link "Delete", to: Routes.post_path(@conn, :delete, post), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Post", to: Routes.post_path(@conn, :new) %></span>

lib/buru_web/templates/post/new.html.eex
<h3>New Post</h3>

<%= render "form.html", Map.put(assigns, :action, Routes.post_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>

lib/buru_web/templates/post/show.html.eex
<h3>Show Post</h3>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @post.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @post.body %>
  </li>

    <li>
    <strong>Category:</strong>
    <%= @category.title %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.post_path(@conn, :edit, @post) %></span>
<span><%= link "Back", to: Routes.post_path(@conn, :index) %></span>
<%= render "comment_form.html", post: @post, changeset: @changeset, action: Routes.post_post_path(@conn, :add_comment, @post) %>
<%= render "comments.html", comments: @post.comments %>